resolver: lts-14.17
packages:
- .
flags:
  vulkan-api:
    useNativeFFI-1-0: true
    useNativeFFI-1-1: false
    useUnsafeFFIDefault: true
extra-deps:
- vulkan-api-1.3.0.0@sha256:9f905a1656c35cf15786a1f2669ab83b8f4633ca35b2affcbb05012958ab12ce
extra-include-dirs:
- extras/vulkansdk-macos-1.1.130.0/macOS/include
extra-lib-dirs:
- extras/vulkansdk-macos-1.1.130.0/macOS/lib
